# Generated by Django 5.0.6 on 2024-07-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.IntegerField(unique=True)),
                ('img_src', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='downloads/')),
            ],
        ),
    ]
