# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - cloudchallenge-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_386e123f2ceb49228e1f066078be9078 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_31030f0bd740456c8dee3059205d7b7c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_386e123f2ceb49228e1f066078be9078 }}/abdullah201897/cbp-task2-backend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cloudchallenge-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cf659b49eac748f7b94aea01c2fa6f66 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_386e123f2ceb49228e1f066078be9078 }}/abdullah201897/cbp-task2-backend:${{ github.sha }}'